---
- name: Deploy Flask application using Docker
  hosts: ec2_servers
  become: yes

  tasks:
    - name: Ensure apt cache is updated
      ansible.builtin.apt:
        update_cache: yes

    - name: Install necessary dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Ensure apt cache is updated after adding Docker repository
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present

    - name: Ensure Docker is started and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Copy application files to server
      ansible.builtin.copy:
        src: ../final_project/
        dest: /home/ubuntu/final_project/
        owner: "ubuntu"
        group: "ubuntu"
        mode: 0755

    - name: Build Docker image
      ansible.builtin.command:
        cmd: docker build -t simple-flask-app /home/ubuntu/final_project/
      args:
        chdir: /home/ubuntu/final_project/

    - name: Ensure Docker container is running
      ansible.builtin.docker_container:
        name: simple-flask-app
        image: simple-flask-app
        state: started
        restart_policy: always
        published_ports:
          - 5000:5000
