name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-flask-app:${{ github.sha }} .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/simple-flask-app:${{ github.sha }}

      - name: Deploy to EC2 with SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Установка Ansible, если он не установлен
            sudo apt update
            sudo apt install -y ansible
            
            # Создание файла playbook
            echo '
            ---
            - name: Deploy Flask application using Docker
              hosts: localhost
              become: yes
              tasks:
                - name: Ensure Docker is installed
                  ansible.builtin.apt:
                    name: docker-ce
                    state: present

                - name: Ensure Docker is started and enabled
                  ansible.builtin.service:
                    name: docker
                    state: started
                    enabled: yes

                - name: Remove old Docker container
                  ansible.builtin.docker_container:
                    name: simple-flask-app
                    state: absent

                - name: Pull Docker image
                  ansible.builtin.docker_image:
                    name: ${{ secrets.DOCKER_USERNAME }}/simple-flask-app
                    tag: ${{ github.sha }}
                    source: pull

                - name: Ensure Docker container is running
                  ansible.builtin.docker_container:
                    name: simple-flask-app
                    image: ${{ secrets.DOCKER_USERNAME }}/simple-flask-app:${{ github.sha }}
                    state: started
                    restart_policy: always
                    published_ports:
                      - 5000:5000
            ' > playbook.yml

            # Выполнение playbook
            ansible-playbook playbook.yml -i localhost
