name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: List directory contents
        run: |
          ls -R

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          cd final_project_app
          docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-flask-app:latest -f Dockerfile .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-flask-app:latest

      - name: Deploy to EC2 with SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Remove existing container if it exists
            sudo docker container rm -f simple-flask-app || true
            # Pull the latest Docker image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/simple-flask-app:latest
            # Run the new container
            sudo docker run -d --name simple-flask-app -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/simple-flask-app:latest
            # Check running containers
            sudo docker ps
