name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-flask-app:${{ github.sha }} -f final_project/final_project_app/Dockerfile .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-flask-app:${{ github.sha }}

      - name: Deploy to EC2 with SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Установка Docker и Ansible на сервере
            sudo apt update
            sudo apt install -y docker.io ansible

            # Удаление старого контейнера
            sudo docker container rm -f simple-flask-app || true

            # Pull нового Docker-образа
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/simple-flask-app:${{ github.sha }}

            # Запуск нового Docker-контейнера
            sudo docker run -d --name simple-flask-app -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/simple-flask-app:${{ github.sha }}

            # Опционально: проверка состояния контейнера
            sudo docker ps
